version: '3.8'
services:
  slack-task-tracker:
    build: .
    container_name: slack-task-tracker
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /app/node_modules
